### GET
GET http://localhost:3000/api/genres

### GET BY ID
GET http://localhost:3000/api/genres/688c24e181d8d11d1658ee2a

### POST
POST http://localhost:3000/api/genres
Content-Type: application/json

{
  "name": "Horror"
}

### PUT
PUT http://localhost:3000/api/genres/688c24d081d8d11d1658ee28
Content-Type: application/json

{
  "name": "Thriller"
}

### DELETE
DELETE http://localhost:3000/api/genres/688c24c981d8d11d1658ee26
